---
# Full LVM configure - includes all steps in order
- include_tasks: install_lvm.yml
- include_tasks: create_disk.yml
- include_tasks: create_pv.yml
- include_tasks: create_vg.yml
- include_tasks: create_lv.yml
- include_tasks: format_mount.yml
- include_tasks: extend_lv.yml
- include_tasks: lvm_summary.yml