---
# Main tasks file for lvm_rhcsa

- name: Clean up LVM configuration
  include_tasks: cleanup.yml
  when: lvm_action | default('configure') == 'clean'

- name: Install and configure LVM
  include_tasks: configure.yml
  when: lvm_action | default('configure') == 'configure'

- name: Add a brand new physical drive to expand the pool  
  include_tasks: add_hd.yml
  when: lvm_action | default('configure') == 'add_hd'
- name: use pvmove to migrate all data off vdb and onto vdc with zero downtime
  include_tasks: pvmove.yml
  when: lvm_action | default('configure') == 'pvmove'