
- name: List block devices for rhcsa-node1
  ansible.builtin.command: virsh domblklist rhcsa-node1
  become: yes
  register: domblklist_output
  changed_when: false

- name: Show the output of domblklist
  ansible.builtin.debug:
    var: domblklist_output.stdout_lines
- name: First, confirm /dev/vdb is actually holding the data and /dev/vdc has enough free space.
  ansible.builtin.command: pvdisplay
  delegate_to: rhcsa-node1
  become: yes
  register: pvdisplay_output
  changed_when: false

- name: Show the output of pvdisplay
  ansible.builtin.debug:
    var: pvdisplay_output.stdout_lines  


- name: Use pvmove to migrate all data off /dev/vdb and onto /dev/vdc with zero downtime
  ansible.builtin.command: pvmove /dev/vdb /dev/vdc
  delegate_to: rhcsa-node1
  become: yes
  register: pvmove_output
  changed_when: false  

- name: Show the output of pvmove
  ansible.builtin.debug:
    var: pvmove_output.stdout_lines   